name: "Nette Tester"

on:
  pull_request:

  push:
    branches: ["*"]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  build84:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@v1
    with:
        php: "8.4"

  build83:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@v1
    with:
        php: "8.3"

  build82:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester-mysql.yml@v1
    with:
        php: "8.2"
